# environment variables
environment:
  nodejs_version: "6.9"

# scripts that run after cloning repository
install:
  # install node 
  
# scripts to run before build
before_build:
  - npm install

build:  
  - ng build 
